### ISSUE TITLE
No comments in code

### ISSUE THREAD

**Issue by angelofallars** [Neoloopy/Monika_Assistant#5]
As you add more features into this project, it may be hard to keep track which line of code does what. Even though you've only written 26 lines, you should consider adding comments.

You should add comments to describe what a line of code does, or better, why that section of code is necessary. This will make it easier to read the code. If you do not add comments, later on it will be difficult to keep track of how your program works.

Commenting and documenting code is good practice. You should make it a habit to add comments to your code.

**Comment by angelofallars** [comment]
I'll close this issue once you've added some comments to your code

**Comment by Neoloopy** [comment]
Added a comment on line 5

**Comment by angelofallars** [comment]
Line 5:
`#haha spaghetti code go brrrrrrr`

Not what I expected, but it seems to describe the current code. Closed. 👍
